# [[file:../../../../tang-server.org::*Image][Image:1]]
FROM quay.io/almalinuxorg/10-minimal:10.2@sha256:ee053be6b73674fdd32ec1dcee1e0b85dc2fa8b2f75976cbf8e72cfda2f718da

RUN microdnf -y install tang \
  && microdnf clean all \
  && rm -rf /var/cache/libdnf5

CMD ["/usr/libexec/tangd", "/var/db/tang"]
# Image:1 ends here
