# [[file:../../../../tang-server.org::*Image][Image:1]]
FROM quay.io/almalinuxorg/10-minimal:10.2@sha256:81cc449abdebd77e91a63e82f2b6ba760c45bfc24f4f6365d2fd72361a82cb4a

RUN microdnf -y install tang \
  && microdnf clean all \
  && rm -rf /var/cache/libdnf5

CMD ["/usr/libexec/tangd", "/var/db/tang"]
# Image:1 ends here
