# [[file:../../../../tang-server.org::*Image][Image:1]]
FROM quay.io/almalinuxorg/10-minimal:10.2@sha256:1c0191d9bcd9fe466dd00552bb05b632ae3923709d1aef974609c347decf7243

RUN microdnf -y install tang \
  && microdnf clean all \
  && rm -rf /var/cache/libdnf5

CMD ["/usr/libexec/tangd", "/var/db/tang"]
# Image:1 ends here
